port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: false
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
secret: ""
dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 223.6.6.6
  nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
  enhanced-mode: fake-ip
  fake-ip-filter:
    # === Local ===
    - "*.lan"
    - "*.local"
    # === Microsoft Windows Serivice ===
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 3600
  icloud:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 3600
  apple:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 3600
  google:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/google.yaml
    interval: 3600
  proxy:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 3600
  direct:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 3600
  private:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 3600
  gfw:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 3600
  greatfire:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 3600
  tld-not-cn:
    type: http
    behavior: domain
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 3600
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 3600
  cncidr:
    type: http
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 3600
  lancidr:
    type: http
    behavior: ipcidr
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 3600
  applications:
    type: http
    behavior: classical
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 3600
rules:
  - RULE-SET,private,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,applications,ğŸ¯ å…¨çƒç›´è¿
  - DOMAIN,yacd.haishan.me,ğŸ¯ å…¨çƒç›´è¿
  - DOMAIN,clash.razord.top,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,telegramcidr,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,tld-not-cn,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,greatfire,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,proxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - DOMAIN,naiko.cloud,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
